# .github/workflows/test.yaml
name: test
on: [ push, pull_request ]
jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        implementation:
          - clfoundation/sbcl:2.2.4
          - clfoundation/ecl:21.2.1
          - clfoundation/ccl:1.12
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.implementation }}
      env:
        CI_SYSTEM: github
        QUICKLISP_ADD_TO_INIT_FILE: true
        QUICKLISP_DIST_VERSION: latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run tests
        run: |
          ./scripts/run-ci-tests.sh
