# .github/workflows/test.yaml
name: test
on: [ push, pull_request ]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      WORKSPACE: /github/workspace/
      QUICKLISP_ADD_TO_INIT_FILE: true
      QUICKLISP_DIST_VERSION: latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run tests
        uses: docker://clfoundation/sbcl:2.2.4
        with:
          args: /github/workspace/scripts/run-ci-tests.sh
